//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoXML
    {
        public int ArchivoXMLID { get; set; }
        public int SolicitudID { get; set; }
        public string NombreArchivoXML { get; set; }
        public byte[] ArchivoXML1 { get; set; }
        public System.DateTime FechaAlmacenamiento { get; set; }
        public Nullable<bool> SeCargoXML { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
