//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public int ComprobanteID { get; set; }
        public int SolicitudID { get; set; }
        public string Nombre { get; set; }
        public byte[] Archivo { get; set; }
        public System.DateTime FechaAlmacenamiento { get; set; }
        public Nullable<bool> SeCargoComprobante { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
