//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public int ConceptoID { get; set; }
        public int TipoPagoID { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> ImporteParcial { get; set; }
        public Nullable<int> SolicitudId { get; set; }
    
        public virtual TipoPago TipoPago { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
