//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int ContactoID { get; set; }
        public int ProveedorID { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public long Telefono1 { get; set; }
        public Nullable<long> Telefono2 { get; set; }
        public string CorreoElectronico1 { get; set; }
        public string CorreoElectronico2 { get; set; }
        public bool EstaActivo { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
