//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSolicitud
    {
        public int DetalleSolicitudID { get; set; }
        public int SolicitudId { get; set; }
        public int PagadoraID { get; set; }
        public string NumeroFactura { get; set; }
        public int NumeroPago { get; set; }
        public decimal ImporteParcial { get; set; }
        public string ImporteLetra { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> Porcentaje { get; set; }
        public Nullable<int> ClienteID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Pagadora Pagadora { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
