//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistribucionGasto
    {
        public int DistribucionGastoID { get; set; }
        public Nullable<int> SolicitudID { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> CentroCostosID { get; set; }
        public Nullable<int> Porc { get; set; }
        public Nullable<decimal> Importe { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
