//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaBancaria
    {
        public int ReferenciaBancariaID { get; set; }
        public int ProveedorID { get; set; }
        public Nullable<int> BancoID { get; set; }
        public int MonedaID { get; set; }
        public string Nombre { get; set; }
        public string Cuenta { get; set; }
        public string Clabe { get; set; }
        public bool EstaActivo { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
